applications:
    front:
        type: apache
        links: [app]
        ports:
            8080: 80
        volumes:
            .: /var/www
        custom:
        #    fastCgi: app
            documentRoot: /var/www/web
            modules: [rewrite]

    app:
        type: php-fpm
        links: [db]
        ports:
            9000: 9000
        volumes:
            .: /var/www
        before_script: bin/init-gaudi-app.sh

    db:
        type: mysql
        ports:
            3306: 3306
        after_script: mysql -e "CREATE DATABASE IF NOT EXISTS symfony CHARACTER SET utf8 COLLATE utf8_general_ci;" -uroot
        volumes:
            .gaudi/mysql: /var/lib/mysql
            
binaries:
    composer:
        type: composer


# $ gaudi run composer create-project symfony/framework-standard-edition sf/ 2.4.0
# $ mv sf/* .
# Create: app/config/parameters.php
#<?php
#$container->setParameter('phpcr_backend', [
#    "type" => "jackrabbit",
#    "url" => 'http://'.getenv('JACKRABBIT_PORT_8082_TCP_ADDR').':'.getenv('JACKRABBIT_PORT_8082_TCP_PORT')."/server/"
#]);

# $ gaudi
