language: go
go:
    - 1.2

script:
    - go get code.google.com/p/go.tools/cmd/goimports
    - go get launchpad.net/gocheck
    - go get github.com/qur/withmock
    - go get github.com/qur/withmock/mocktest
    - export PATH=$GOPATH/bin:$PATH

    - cd $HOME/gopath/src/github.com/marmelab/gaudi/container && withmock go test -v
    - cd $HOME/gopath/src/github.com/marmelab/gaudi/maestro && withmock go test -v
    - cd $HOME/gopath/src/github.com/marmelab/gaudi/tests && withmock go test -v
