applications:
    couchdb:
        type: index
        image: klaemo/couchdb
        volumes:
            .gaudi/couchdb: /usr/local/var/lib/couchdb
        ports:
            5984: 5984

    app:
        type: nodejs
        links: [couchdb]
        volumes:
            .: /app
        after_script: node /app/app.js
        custom:
            modules: [cradle]
