applications:   
    worker1:
        extends: producer
        after_script: python /app/worker.py
        
    worker2:
        extends: producer
        after_script: python /app/worker.py
        
    producer:
        type: python
        links: [rabbitmq]
        volumes:
            .: /app
        after_script: python /app/producer.py
        custom:
            version: 2.7.6
            pip_modules: [pika==0.9.8]

    rabbitmq:
        type: rabbitmq
        environments:
            USER: docker
            PASS: docker
            DB: project
        ports:
            5672: 5672
            15672: 15672
            4369: 4369
