applications:
    lb:
        type: varnish
        ports:
            8080: 80
        links: [front1, front2]
        volumes:
            .: /app
        custom:
            backends: [front1, front2]
            probe_url: /up.php

    front1:
        type: apache
        links: [app1]
        ports:
            8081: 8080
        volumes:
            .: /app
        modules: [rewrite]
        custom:
            fastCgi: app1
            fastCgiIdleTimeout: 500
            documentRoot: /app/htdocs

    front2:
        type: apache
        links: [app2]
        ports:
            8082: 8080
        volumes:
            .: /app
        modules: [rewrite]
        custom:
            fastCgi: app2
            fastCgiIdleTimeout: 500
            documentRoot: /app/htdocs

    app1:
        type: hhvm
        ports:
            9000: 9000
        volumes:
            .: /app
        apt_get: [php5-gd, php5-intl]
        links: [memcached]
        custom:
            memoryLimit: 512M
            maxExecutionTime: 500

    app2:
        type: php-fpm
        ports:
            9001: 9000
        volumes:
            .: /app
        apt_get: [php5-gd, php5-intl]
        links: [memcached]
        custom:
            memoryLimit: 512M
            maxExecutionTime: 500

    master:
        type: mysql
        ports:
            3306: 3306
        volumes:
            /var/tmp/data/master: /var/lib/mysql
        after_script:
            mysql -e "CREATE DATABASE IF NOT EXISTS magento CHARACTER SET utf8 COLLATE utf8_general_ci;"
        custom:
            repl: master

    slave1:
        type: mysql
        ports:
            3307: 3306
        volumes:
            /var/tmp/data/slave1: /var/lib/mysql
            /var/tmp/data/master: /var/lib/mysql-master
        links: [master]
        custom:
            repl: slave
            master: master

    slave2:
        type: mysql
        ports:
            3308: 3306
        volumes:
            /var/tmp/data/slave2: /var/lib/mysql
            /var/tmp/data/master: /var/lib/mysql-master
        links: [master]
        custom:
            repl: slave
            master: master

    memcached:
        type: index
        image: borja/docker-memcached
        ports:
            11211: 11211

    phpmyadmin:
        type: phpmyadmin
        ports:
            80: 80
        links: [master]
