applications:
    front:
        type: apache
        links: [app]
        ports:
            8080: 80
        volumes:
            .: /var/www
        custom:
            fastCgi: app
            documentRoot: /var/www/web
            modules: [rewrite]

    app:
        type: hhvm
        ports:
            9000: 9000
        volumes:
            .: /var/www
        custom:
            modules: []

binaries:
    composer:
        type: composer

# sudo gaudi
# sudo gaudi run composer update
