applications:
    app:
        type: ror
        volumes:
            .: /app
        ports:
            8080: 8080
        links: [db]
        custom:
            project_name: ror
            documentRoot: /app/ror/public
            serverType: apache

    db:
            type: mysql
            ports:
                3306: 3306
            after_script: mysql -e "CREATE DATABASE IF NOT EXISTS ror_development CHARACTER SET utf8 COLLATE utf8_general_ci;" -uroot
            volumes:
                .gaudi/mysql: /var/lib/mysql
